export const REQUESTING = "REQUESTING";
export const DONE_REQUESTING = "DONE_REQUESTING";
export const SET_CANVAS = "SET_CANVAS";
export const CLEAR_CANVAS = "CLEAR_CANVAS";
export const SET_CHATS = "SET_CHATS";
export const SET_CHAT_SUBSCRIPTION = "SET_CHAT_SUBSCRIPTION";
export const SET_CANVAS_SUBSCRIPTION = "SET_CANVAS_SUBSCRIPTION";
